#!/usr/bin/env bash
# Configuring nginx and modifying the current page content.

sudo apt-get update
sudo apt-get install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service restart nginx
