#!/usr/bin/env bash
# Configuring nginx and modifying the current page content.

sudo apt update
sudo apt install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx start
