#!/usr/bin/env bash
# Configuring nginx and modifying the current page content.

sudo apt update
sudo apt -y install nginx
echo "Hello World" > index.html
sudo mv index.html /var/www/html/
sudo service nginx restart
