#!/usr/bin/env bash
# Configuring a Nginx server so that /redirect_me is redirecting to another page.

sudo apt -y update
sudo apt -y install nginx
echo "Hello World" > index.html
sudo mv index.html /var/www/html/
sudo sed -i "listen [::]:80 default_server rewrite ^/redirect_me https://github.com/DevPacho permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
