#!/usr/bin/env bash
# Configuring a Nginx server so that /redirect_me is redirecting to another page.

sudo apt -y update
sudo apt -y install nginx
echo "Hello World" > index.html
sudo mv index.html /var/www/html/
sed -i "location /redirect_me {\n return 301 https://github.com/DevPacho;\n}\n" /etc/nginx/sites-enabled/default
sudo service nginx restart
