#!/usr/bin/env bash
# Configuring a Nginx server so that /redirect_me is redirecting to another page.

sudo apt -y update
sudo apt -y install nginx
echo "Hello World" > index.html
sudo mv index.html /var/www/html/
sed -i "s/\/redirect_me/https:\/\/www.youtube.com\/watch\?v\=QH2-TGUlwu4 permanent" /etc/nginx/sites-available/default
sudo service nginx restart
