#!/usr/bin/env bash
# Configuring a Nginx server to have a custom 404 page.

sudo apt -y update
sudo apt -y install nginx
echo "Ceci n'est pas une page" > my404error.html
sudo mv my404error.html /var/www/html/
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me my404error.html =404;" /etc/nginx/sites-available/default
sudo service nginx restart
