#!/usr/bin/env bash
# Adding a custom Nginx response header.

sudo apt -y update
sudo apt -y install nginx
echo "Hello World" > index.html
sudo mv index.html /var/www/html/
echo "Ceci n'est pas une page" > my404error.html
sudo mv my404error.html /var/www/html/
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://github.com/DevPacho permanent;" /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server;/ a error_page 404 /my404error.html;" /etc/nginx/sites-available/default
sudo sed -i "/# as directory, then fall back to displaying a 404./ a add_header X-Served-By $HOSTNAME" /etc/nginx/sites-available/default
sudo service nginx restart
