#!/usr/bin/env bash
# Script that contains the classic 'FizzBuzz' program on Bash.

for number in {0..100}
do
    if [ $((number % 3)) -eq 0 ] && [ $((number % 5)) -eq 0 ]
    then
        echo "FizzBuzz"

    elif [ $((number % 3)) -eq 0 ]
    then
        echo "Fizz"

    elif [ $((number % 5)) -eq 0 ]
    then
        echo "Buzz"

    else
        echo "$number"
    fi
done
